biblio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from contact.views import MessageAddView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^shelf/', include('shelf.urls', namespace='shelf')),
    url(r'^contact/$', MessageAddView.as_view())
]


"""biblio URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

shelf/urls.py
from django.conf.urls import url

from shelf.views import AuthorListView, AuthorDetailView, BookListView, BookDetailView

urlpatterns = [
    url(r'^autorzy/$', AuthorListView.as_view(), name='author-list'),

    url(r'^autorzy/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author-detail'),
    url(r'^ksiazki/$', BookListView.as_view(), name='book-list'),
    url(r'^ksiazki/(?P<pk>\d+)/$', BookDetailView.as_view(), name='book-list'),

]

admin/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

shelf/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _



class Author(models.Model):
    first_name = models.CharField( _("first name"),max_length = 20)
    last_name = models.CharField(max_length = 20)
    def __str__(self):
        return '{first_name}{last_name}'.format(first_name = self.first_name,last_name= self.last_name)

    class Meta:
        ordering = ('last_name', 'first_name')
        verbose_name = _('author')
        verbose_name_plural = _('authors')


class Publisher(models.Model):
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name


class BookCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Book(models.Model):
    """cos w w rodzaju rekopisu"""

    title = models.CharField(max_length = 100)
    # author = models.ForeignKey("Author")
    author = models.ManyToManyField(Author)
    categories = models.ManyToManyField(BookCategory)

    def __str__(self):
        return self.title

class BookEdition(models.Model):
    """
    Wydanie okreslonej ksiazki
    """
    book = models.ForeignKey(Book)
    isbn = models.CharField(max_length = 17)
    publisher = models.ForeignKey("Publisher")

    def __str__(self):
        return "{book.title},{publisher.name}".format(book=self.book,
                                                      publisher=self.publisher)
COVER_TYPES = (
    ('soft','Soft'),
    ('hard','Hard'),
    # (wartosc w bazie, wartosc wyswietlania)
)

class BookItem(models.Model):
    """
    Konkretny egzemplarz
    """
    edition = models.ForeignKey(BookEdition)
    catalogue_number = models.CharField(max_length=30)
    cover_type = models.CharField(max_length=30,choices=COVER_TYPES)

    def __str__(self):
        return "{edition},{cover}".format(edition=self.edition, cover= self.get_cover_type_display())

admin/views.py
from django.shortcuts import render

# Create your views here.

shelf/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Author, Book

class AuthorListView(ListView):
    model = Author

class AuthorDetailView (DetailView):
    model = Author

class BookListView(ListView):
    model = Book

class BookDetailView(DetailView):
    model = Book

shelf/templates/shelf/author_detail.html
{% extends "base.html" %}

{% block 'content' %}

<div><a href="{% url 'shelf:author-list' %}">Powrot do listy autorow</a></div>

Profil autora: {{object.first_name}}, {{object.last_name}}
<h2> Ksiazki:</h2>
<ul>
{% for book in object.book_set.all %}
    <li><a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

shelf/templates/shelf/author_list.html
{% extends "base.html" %}

{% block 'content' %}
<ul>
    {% for author in object_list %}
    <li><a href="{% url 'shelf:author-detail' author.id %}"> {{author.first_name}}</a> </li>

{% endfor %}
</ul>

{% endblock %}

shelf/templates/shelf/book_detail.html
{% extends "base.html" %}

{% block 'content' %}
<a href="{% url 'shelf:book-list' %}"> Powrot do list ksiazek </a>
<h1>{{object.title}}</h1>

{% endblock %}

shelf/templates/shelf/book_list.html
{% extends "base.html" %}
{% block 'content' %}
<ul>
    {% for book in object_list %}
    <li><a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }}</a> -
        {% for author in book.author_set.all %}
            {{ author.first_name }} {{ author.last_name }}
        {% if not forloop.last %},{% endif %}
        <!-- bedzie odzielal przecinkiem az to nie bedzie ostatni obiekt -->
        {% endfor %}

    </li>
    {% endfor %}
</ul>


{% endblock %}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title> brak tytulu </title>
    <meta http-equiv="content-type" content="text/html;charset=utf-8"/>
    <meta name="generator"content="Geany 1.24.1"/>
</head>
<body>
    <!-- tresc strony tutaj -->
    {% block 'content' %}
    {% endblock %}

</body>

</html>